CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
deepspeed --master_port 11451 llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path  /home/Clawmachine/checkpoints/lang-only-mirage-7b-continuv-merged \
    --version v1 \
    --data_path /homeClawmachine/Data/MIRAGE/llava_mix_coco_gqa.json \
    --image_folder ./playground/data \
    --vision_tower /home/MaTianren/LaVIT-7B-v2 \
    --pretrain_mm_mlp_adapter /home/Clawmachine/checkpoints/clawmachine-7b-continuv-pretrain/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/clawmachine-s2 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 1e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True 
